name: 'TestProj'
description: 'Takes a parameter and executes python script'
author: Sebi1011

inputs:
  platform:
    description: 'ios/flutter'
    required: true
    default: 'flutter'
  PROJECT-PATH:
    description: 'path to project'
    required: true

runs:
  using: "composite"
  steps:
    - name: Call parameter
      shell: bash
      run: |
        echo "${{ github.event.inputs.platform }}"
        echo "${{ github.event.inputs.PROJECT-PATH }}"

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Run Python Script
      shell: bash
      run: python ${{ github.action_path }}/src/call_paths.py --dir ${{ inputs.PROJECT-PATH }} --platform ${{ inputs.platform }}
